# on:
#   pull_request:
#     branches:
#       - main

# event
on:
  push:
    branches:
      - add_test_to_git

jobs:
  run_jest_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '21'

    - name: Get Github action IP
      id: ip
      uses: haythem/public-ip@v1.2

    - name: Add Github Actions IP to Security group
      # documentation: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/authorize-security-group-ingress.html
      run: |
        aws ec2 authorize-security-group-ingress --group-id sg-05b3ccb32f4ffc8ed --protocol tcp --port 5432 --cidr ${{ steps.ip.outputs.ipv4 }}/32
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: install all backend dependencies
      run: cd backend && npm install

    - name: Run Jest tests
      run: cd backend && npm test

    - name: Remove Github Actions IP from security group
    # documentation: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/revoke-security-group-ingress.html
      run: |
        aws ec2 revoke-security-group-ingress --group-id sg-05b3ccb32f4ffc8ed --protocol tcp --port 5432 --cidr ${{ steps.ip.outputs.ipv4 }}/32
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      if: always()

